export const disabilitados = {
    'Codigo': false,
    'Descripcion': false,
    'Tipo Fabricante': false,
    'Referencia Fabricante': false,
    'Marca': false,
    'Unidad de Compra': false,
    'Fecha actualizacion': true,
    'Precio de Lista': false,
    'Descuento Basico': false,
    'Descuento Proyectos': false,
    'Precio con Descuento': true,
    'Precio con Descuento Proyecto': true,
    'Precio Ultima Compra': false,
    'Precios de Listas': false,
    'Ruta Tiempos': false,
    'Tiempos Chapisteria': false,
};
export const requeridos = {
    'Codigo': true,
    'Descripcion': true,
    'Tipo Fabricante': true,
    'Referencia Fabricante': true,
    'Marca': true,
    'Unidad de Compra': true,
    'Fecha actualizacion': false,
    'Precio de Lista': true,
    'Descuento Basico': true,
    'Descuento Proyectos': true,
    'Precio con Descuento': false,
    'Precio con Descuento Proyecto': false,
    'Precio Ultima Compra': false,
    'Precios de Listas': true,
    'Ruta Tiempos': true,
    'Tiempos Chapisteria': true,
};